import type { Course } from "./types";
import { courseChapterMap } from "./courseChapters";

/**
 * 课程数据（机械工程专业，覆盖不同年级与课程类型）
 *
 * `knowledgeNodeIds` 指向合并后的能力—知识点谱系，与 `knowledgeGraph` / `courseCoverage` 对齐。
 * `chapters` 引用 `courseChapters.ts` 中的章节数据。
 *
 * 数据闭环：
 * - courseId 被教学计划 (teachingPlans.ts) 引用，如 plan-main.courseId = "course-mech-draw"
 * - 章节 knowledgePointIds/skillPointIds 引用 kgL3.ts 的 L3Node ID
 * - 章节课件/参考资料引用 resources.ts 的 Resource ID
 */

export const courses: Course[] = [
  {
    id: "course-mech-draw",
    name: "机械制图与CAD",
    coverUrl: "/covers/course-mech-draw.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-drawing",
    description:
      "以国家最新制图标准为纲，系统讲授投影原理、机件表达、零件图装配图与 CAD 工程制图，是机械类专业的核心技术基础课。",
    credit: 4,
    totalHours: 64,
    semester: "2026春季",
    knowledgeNodeIds: [
      "kn-mech-001",
      "kn-mech-002",
      "kn-mech-003",
      "kn-mech-004",
      "kn-mech-005",
      "kn-mech-006",
      "kn-mech-007",
      "kn-mech-010",
      "kn-mech-011",
      "kn-mech-018",
    ],
    ownerTeacherId: "t-li",
    tags: ["核心课", "制图", "CAD", "工科基础"],
    courseType: "专业基础课",
    publishStatus: "published",
    publishedAt: "2026-01-15T10:00:00+08:00",
    summary: "系统讲授投影原理、机件表达、零件图装配图与CAD工程制图，机械类核心基础课。",
    chapters: courseChapterMap["course-mech-draw"],
  },
  {
    id: "course-mech-design",
    name: "机械设计基础",
    coverUrl: "/covers/course-mech-design.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-design",
    description:
      "研究通用机械零件与常用机构的工作原理和设计方法，为后续专业课程奠定机械设计能力基础。",
    credit: 4,
    totalHours: 64,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-007", "kn-mech-008", "kn-mech-009", "kn-mech-010"],
    ownerTeacherId: "t-chen",
    tags: ["核心课", "机械设计"],
    courseType: "专业课",
    publishStatus: "published",
    publishedAt: "2026-01-18T10:00:00+08:00",
    summary: "通用机械零件与常用机构的工作原理和设计方法，奠定机械设计能力基础。",
    chapters: courseChapterMap["course-mech-design"],
    aiSuggestion: {
      kind: "add_resource",
      summary: "建议补充题库与微课，覆盖截交/相贯与三维—工程图衔接节点",
      reason:
        "最新能力谱系在「截交线与相贯线」「三维特征—装配—工程图」「AutoCAD 出图」上加深了与零件设计的耦合；当前课程挂载点偏少，学生完成大作业时上述环节错误集中，需配套可练可测资源。",
      uncoveredNodeIds: ["kn-mech-006", "kn-mech-011", "kn-mech-012"],
      suggestedResourceTypes: ["video", "quiz"],
      generatedAt: "2026-03-28T10:00:00+08:00",
    },
  },
  {
    id: "course-mech-practice",
    name: "金工实习",
    coverUrl: "/covers/course-mech-practice.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-manu",
    description:
      "走入车间，体验车、铣、钳、焊、铸的全流程金属加工实践，重在动手与工程规范养成。",
    credit: 2,
    totalHours: 40,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-013", "kn-mech-009", "kn-mech-008"],
    ownerTeacherId: "t-wang",
    tags: ["实训", "工程规范"],
    courseType: "实训课",
    publishStatus: "published",
    publishedAt: "2026-01-20T10:00:00+08:00",
    summary: "车铣钳焊铸全流程金属加工实践，重在动手与工程规范养成。",
    chapters: courseChapterMap["course-mech-practice"],
  },
  {
    id: "course-mech-intro",
    name: "机械工程专业导论",
    coverUrl: "/covers/course-mech-intro.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-intro",
    description:
      "面向大一新生：产业链概览、专业培养方案、制图与智能制造入门，建立后续课程的认知地图。",
    credit: 1,
    totalHours: 16,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-018", "kn-mech-003", "kn-mech-016", "kn-mech-017"],
    ownerTeacherId: "t-sun",
    tags: ["大一", "导论"],
    courseType: "导论课",
    publishStatus: "published",
    publishedAt: "2026-01-12T10:00:00+08:00",
    summary: "产业链概览、培养方案、制图与智能制造入门，建立课程认知地图。",
    chapters: courseChapterMap["course-mech-intro"],
  },
  {
    id: "course-mech-tolerance",
    name: "互换性与技术测量",
    coverUrl: "/covers/course-mech-tolerance.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-tolerance",
    description:
      "系统学习尺寸公差、形位公差、表面粗糙度及几何量检测方法，支撑零件图与工艺设计。",
    credit: 3,
    totalHours: 48,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-008", "kn-mech-009", "kn-mech-015"],
    ownerTeacherId: "t-wanglh",
    tags: ["大四", "公差", "检测"],
    courseType: "专业课",
    publishStatus: "published",
    publishedAt: "2026-01-22T10:00:00+08:00",
    summary: "尺寸公差、形位公差、表面粗糙度及几何量检测方法。",
    chapters: courseChapterMap["course-mech-tolerance"],
  },
  {
    id: "course-mech-robotics",
    name: "工业机器人技术应用基础",
    coverUrl: "/covers/course-mech-robotics.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-robot",
    description:
      "坐标系与示教编程、典型搬运/码垛工作站、安全互锁与离线仿真入门，与制图课中的三维建模衔接。",
    credit: 2,
    totalHours: 32,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-012", "kn-mech-014", "kn-mech-016", "kn-mech-010"],
    ownerTeacherId: "t-zhao",
    tags: ["大二", "机器人", "仿真"],
    courseType: "选修课",
    publishStatus: "draft",
    summary: "坐标系与示教编程、工作站应用、安全互锁与离线仿真入门。",
    chapters: courseChapterMap["course-mech-robotics"],
  },
  {
    id: "course-mech-hydraulic",
    name: "液压与气压传动",
    coverUrl: "/covers/course-mech-hydraulic.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-hydraulic",
    description:
      "流体传动基础、典型压力/速度控制回路、气动元件选型与系统装调，服务机电液一体化设计。",
    credit: 3,
    totalHours: 48,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-015", "kn-mech-010"],
    ownerTeacherId: "t-zhao",
    tags: ["专业课", "液压气动"],
    courseType: "专业课",
    publishStatus: "published",
    publishedAt: "2026-01-25T10:00:00+08:00",
    summary: "流体传动基础、典型控制回路、气动元件选型与系统装调。",
    chapters: courseChapterMap["course-mech-hydraulic"],
  },
  {
    id: "course-mech-process",
    name: "机械制造工艺学",
    coverUrl: "/covers/course-mech-process.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-process",
    description:
      "工艺规程制定、定位夹紧、加工误差与装配工艺，强调从图纸到批产的质量与成本意识。",
    credit: 3,
    totalHours: 48,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-009", "kn-mech-013", "kn-mech-010", "kn-mech-017"],
    ownerTeacherId: "t-wanglh",
    tags: ["制造工艺", "质量"],
    courseType: "专业课",
    publishStatus: "published",
    publishedAt: "2026-01-28T10:00:00+08:00",
    summary: "工艺规程制定、定位夹紧、加工误差与装配工艺，图纸到批产的质量意识。",
    chapters: courseChapterMap["course-mech-process"],
    aiSuggestion: {
      kind: "adjust_hours",
      summary: "建议总学时 +8，承接「智能制造孪生」与「机器人工作站」在工艺链里的课堂演练",
      reason:
        "图谱迭代后，工艺学需显式对齐产线数字孪生与机器人节拍安全等知识点；若维持现学时，综合工艺大课只能点到为止，建议在本专业课程委员会备案后增加 8 学时用于案例拆解与课内实作。",
      uncoveredNodeIds: ["kn-mech-016", "kn-mech-014"],
      suggestedHoursDelta: 8,
      generatedAt: "2026-03-28T10:00:00+08:00",
    },
  },
  {
    id: "course-mech-ai-lab",
    name: "学科内 AI 实训与应用",
    coverUrl: "/covers/course-mech-intro.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-ai",
    description:
      "在制图、设计、工艺与机电类课程场景中，学习选用对话式大模型、文生图等工具完成指定作业与小型任务，强调事实核验、国标意识与学术诚信。",
    credit: 1,
    totalHours: 16,
    semester: "2026春季",
    knowledgeNodeIds: [
      "kn-mech-017",
      "kn-mech-016",
      "kn-mech-009",
      "kn-mech-011",
      "kn-mech-012",
      "kn-mech-015",
    ],
    ownerTeacherId: "t-sun",
    tags: ["AI实训", "生成式AI", "跨课程"],
    courseType: "实训课",
    publishStatus: "draft",
    summary: "学习选用AI工具完成制图/设计/工艺任务，强调事实核验与学术诚信。",
    chapters: courseChapterMap["course-mech-ai-lab"],
    aiSuggestion: {
      kind: "add_resource_and_hours",
      summary: "需同步补充组合体案例与线上题库，并增加 8 学时用于人机协同实训",
      reason:
        "图谱对比显示「组合体分析与表征」「专业图谱路径意识」仍落在制图主线能力上，本课目前缺少结构化实训脚手架；同时课堂实作时间紧张，建议加学时并引入分层题库与微课，支撑 AI 辅助学习的核验训练。",
      uncoveredNodeIds: ["kn-mech-005", "kn-mech-006", "kn-mech-018"],
      suggestedHoursDelta: 8,
      suggestedResourceTypes: ["video", "quiz", "ppt"],
      generatedAt: "2026-03-28T10:00:00+08:00",
    },
  },
];
