import type { Course } from "./types";

/**
 * 课程数据（机械工程专业，覆盖不同年级与课程类型）
 *
 * 主线核心课：《机械制图与CAD》及关联设计/金工课保持不变。
 */
export const courses: Course[] = [
  {
    id: "course-mech-draw",
    name: "机械制图与CAD",
    coverUrl: "/covers/course-mech-draw.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-drawing",
    description:
      "以国家最新制图标准为纲，系统讲授投影原理、机件表达、零件图装配图与 CAD 工程制图，是机械类专业的核心技术基础课。",
    credit: 4,
    totalHours: 64,
    semester: "2026春季",
    knowledgeNodeIds: [
      "kn-mech-001", "kn-mech-002", "kn-mech-003", "kn-mech-004", "kn-mech-005", "kn-mech-006",
      "kn-mech-007", "kn-mech-008", "kn-mech-009", "kn-mech-010", "kn-mech-011",
      "kn-mech-012", "kn-mech-013", "kn-mech-014", "kn-mech-015", "kn-mech-016",
      "kn-mech-017", "kn-mech-018", "kn-mech-019", "kn-mech-020", "kn-mech-021", "kn-mech-022", "kn-mech-023",
      "kn-mech-024", "kn-mech-025", "kn-mech-026", "kn-mech-027", "kn-mech-028", "kn-mech-029",
      "kn-mech-030", "kn-mech-031", "kn-mech-032", "kn-mech-033", "kn-mech-034",
      "kn-mech-035", "kn-mech-036", "kn-mech-037", "kn-mech-038", "kn-mech-039", "kn-mech-040", "kn-mech-041",
      "kn-mech-042", "kn-mech-043", "kn-mech-044", "kn-mech-045", "kn-mech-046", "kn-mech-047",
      "kn-mech-048", "kn-mech-049", "kn-mech-050", "kn-mech-051", "kn-mech-052", "kn-mech-053",
      "kn-mech-054", "kn-mech-055", "kn-mech-056", "kn-mech-057", "kn-mech-058", "kn-mech-059", "kn-mech-060",
    ],
    ownerTeacherId: "t-li",
    tags: ["核心课", "制图", "CAD", "工科基础"],
  },
  {
    id: "course-mech-design",
    name: "机械设计基础",
    coverUrl: "/covers/course-mech-design.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-design",
    description:
      "研究通用机械零件与常用机构的工作原理和设计方法，为后续专业课程奠定机械设计能力基础。",
    credit: 4,
    totalHours: 64,
    semester: "2026春季",
    knowledgeNodeIds: [
      "kn-mech-042", "kn-mech-043", "kn-mech-044", "kn-mech-045", "kn-mech-046", "kn-mech-047",
      "kn-mech-048", "kn-mech-049", "kn-mech-050", "kn-mech-051",
    ],
    ownerTeacherId: "t-chen",
    tags: ["核心课", "机械设计"],
  },
  {
    id: "course-mech-practice",
    name: "金工实习",
    coverUrl: "/covers/course-mech-practice.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-manu",
    description:
      "走入车间，体验车、铣、钳、焊、铸的全流程金属加工实践，重在动手与工程规范养成。",
    credit: 2,
    totalHours: 40,
    semester: "2026春季",
    knowledgeNodeIds: [
      "kn-mech-048",
      "kn-mech-049",
      "kn-mech-050",
      "kn-mech-052",
      "kn-mech-061",
      "kn-mech-062",
    ],
    ownerTeacherId: "t-wang",
    tags: ["实训", "工程规范"],
  },
  {
    id: "course-mech-intro",
    name: "机械工程专业导论",
    coverUrl: "/covers/course-mech-intro.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-intro",
    description:
      "面向大一新生：产业链概览、专业培养方案、制图与智能制造入门，建立后续课程的认知地图。",
    credit: 1,
    totalHours: 16,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-001", "kn-mech-002", "kn-mech-003", "kn-mech-004", "kn-mech-012", "core-mech-001"],
    ownerTeacherId: "t-sun",
    tags: ["大一", "导论"],
  },
  {
    id: "course-mech-tolerance",
    name: "互换性与技术测量",
    coverUrl: "/covers/course-mech-tolerance.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-tolerance",
    description:
      "系统学习尺寸公差、形位公差、表面粗糙度及几何量检测方法，支撑零件图与工艺设计。",
    credit: 3,
    totalHours: 48,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-048", "kn-mech-049", "kn-mech-050", "kn-mech-051", "sk-mech-006"],
    ownerTeacherId: "t-wanglh",
    tags: ["大四", "公差", "检测"],
  },
  {
    id: "course-mech-robotics",
    name: "工业机器人技术应用基础",
    coverUrl: "/covers/course-mech-robotics.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-robot",
    description:
      "坐标系与示教编程、典型搬运/码垛工作站、安全互锁与离线仿真入门，与制图课中的三维建模衔接。",
    credit: 2,
    totalHours: 32,
    semester: "2026春季",
    knowledgeNodeIds: [
      "kn-mech-052",
      "kn-mech-054",
      "kn-mech-058",
      "kn-mech-059",
      "kn-mech-060",
      "kn-mech-063",
      "kn-mech-064",
      "sk-mech-003",
    ],
    ownerTeacherId: "t-zhao",
    tags: ["大二", "机器人", "仿真"],
  },
  {
    id: "course-mech-hydraulic",
    name: "液压与气压传动",
    coverUrl: "/covers/course-mech-hydraulic.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-hydraulic",
    description:
      "流体传动基础、典型压力/速度控制回路、气动元件选型与系统装调，服务机电液一体化设计。",
    credit: 3,
    totalHours: 48,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-042", "kn-mech-043", "kn-mech-044", "kn-mech-052", "kn-mech-053"],
    ownerTeacherId: "t-zhao",
    tags: ["专业课", "液压气动"],
  },
  {
    id: "course-mech-process",
    name: "机械制造工艺学",
    coverUrl: "/covers/course-mech-process.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-process",
    description:
      "工艺规程制定、定位夹紧、加工误差与装配工艺，强调从图纸到批产的质量与成本意识。",
    credit: 3,
    totalHours: 48,
    semester: "2026春季",
    knowledgeNodeIds: ["kn-mech-048", "kn-mech-049", "kn-mech-050", "kn-mech-052", "kn-mech-053", "sk-mech-007"],
    ownerTeacherId: "t-wanglh",
    tags: ["制造工艺", "质量"],
  },
  {
    id: "course-mech-ai-lab",
    name: "学科内 AI 实训与应用",
    coverUrl: "/covers/course-mech-intro.jpg",
    professionId: "prof-mech",
    subjectId: "subj-mech-ai",
    description:
      "在制图、设计、工艺与机电类课程场景中，学习选用对话式大模型、文生图等工具完成指定作业与小型任务，强调事实核验、国标意识与学术诚信。",
    credit: 1,
    totalHours: 16,
    semester: "2026春季",
    knowledgeNodeIds: [
      "kn-mech-065",
      "kn-mech-066",
      "kn-mech-067",
      "sk-mech-008",
      "kn-mech-048",
      "kn-mech-054",
      "kn-mech-058",
      "core-mech-003",
      "core-mech-004",
    ],
    ownerTeacherId: "t-sun",
    tags: ["AI实训", "生成式AI", "跨课程"],
  },
];
