import type { Resource } from "./types";

/**
 * 教学资源数据（~45 条，全类型覆盖）
 *
 * 类型覆盖：doc / ppt / video / audio / image / code / dataset / quiz
 * 主线课程《机械制图与CAD》的资源最多、最细。
 * 每个资源可挂载多个知识点（多对多）。
 */
export const resources: Resource[] = [
  // ==================== 机械工程 · 制图基础 ====================
  {
    id: "res-m-001",
    title: "GB/T 14689-2008 技术制图 图纸幅面和格式（全文）",
    type: "doc",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-001", "kn-mech-006"],
    courseIds: ["course-mech-draw"],
    description: "国家标准全文 PDF，机械工程学生必备基础文件。",
    sizeMb: 1.4,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-01T08:10:00+08:00",
    thumbnailUrl: "/thumbs/res-m-001.png",
    tags: ["国标", "必读"],
  },
  {
    id: "res-m-002",
    title: "制图基础概述 · 第一讲课件",
    type: "ppt",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-001", "kn-mech-002", "kn-mech-003", "kn-mech-004", "kn-mech-005"],
    courseIds: ["course-mech-draw"],
    description: "李建国老师经典 PPT，覆盖图幅/比例/字体/图线/尺寸。",
    sizeMb: 8.6,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-01T09:00:00+08:00",
    thumbnailUrl: "/thumbs/res-m-002.png",
    tags: ["课件", "制图基础"],
  },
  {
    id: "res-m-003",
    title: "工程字长仿宋体书写示范",
    type: "video",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-003"],
    courseIds: ["course-mech-draw"],
    description: "8 分钟手把手示范工程字书写。",
    duration: "08:12",
    sizeMb: 55,
    uploaderTeacherId: "t-wang",
    uploadedAt: "2025-09-03T10:30:00+08:00",
    thumbnailUrl: "/thumbs/res-m-003.png",
    tags: ["示范", "视频"],
  },
  {
    id: "res-m-004",
    title: "九种基本图线速查图",
    type: "image",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-004"],
    courseIds: ["course-mech-draw"],
    description: "一张图帮学生对齐图线使用规则。",
    sizeMb: 0.8,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-04T14:20:00+08:00",
    thumbnailUrl: "/thumbs/res-m-004.png",
    tags: ["速查", "图线"],
  },

  // ==================== 机械工程 · 几何作图 ====================
  {
    id: "res-m-010",
    title: "圆弧连接 20 例精讲",
    type: "doc",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-008", "kn-mech-007"],
    courseIds: ["course-mech-draw"],
    description: "从两直线圆弧连接到复杂过渡，20 例经典题解。",
    sizeMb: 4.2,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-10T09:00:00+08:00",
    tags: ["习题", "几何作图"],
  },
  {
    id: "res-m-011",
    title: "椭圆四心近似法动画演示",
    type: "video",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-009"],
    courseIds: ["course-mech-draw"],
    description: "6 分钟动画说清四心圆弧法作椭圆原理。",
    duration: "06:18",
    sizeMb: 35,
    uploaderTeacherId: "t-wang",
    uploadedAt: "2025-09-11T15:20:00+08:00",
    tags: ["动画", "几何"],
  },

  // ==================== 机械工程 · 投影基础 ====================
  {
    id: "res-m-020",
    title: "三视图形成动态演示",
    type: "video",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-014", "kn-mech-015"],
    courseIds: ["course-mech-draw"],
    description: "三投影面展开过程的 3D 动画。",
    duration: "05:42",
    sizeMb: 42,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-18T10:00:00+08:00",
    thumbnailUrl: "/thumbs/res-m-020.png",
    tags: ["动画", "核心"],
  },
  {
    id: "res-m-021",
    title: "长对正高平齐宽相等口诀解析",
    type: "audio",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-015"],
    courseIds: ["course-mech-draw"],
    description: "4 分钟播客，通勤也能复习。",
    duration: "04:05",
    sizeMb: 3.8,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-18T11:00:00+08:00",
    tags: ["播客", "口诀"],
  },
  {
    id: "res-m-022",
    title: "投影基础练习题库（100 题）",
    type: "quiz",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-013", "kn-mech-014", "kn-mech-015"],
    courseIds: ["course-mech-draw"],
    description: "含选择题 60 + 判断题 20 + 读图题 20。",
    sizeMb: 2.1,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-20T13:00:00+08:00",
    tags: ["题库", "投影"],
  },

  // ==================== 机械工程 · 点线面投影 ====================
  {
    id: "res-m-030",
    title: "点线面投影互动课件（H5）",
    type: "ppt",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-017", "kn-mech-019", "kn-mech-021"],
    courseIds: ["course-mech-draw"],
    description: "可拖动点/线/面观察三视图变化的互动课件。",
    sizeMb: 18,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-25T09:30:00+08:00",
    thumbnailUrl: "/thumbs/res-m-030.png",
    tags: ["互动", "课件"],
    isAiGenerated: true,
  },

  // ==================== 机械工程 · 立体与组合体（主故事线重点） ====================
  {
    id: "res-m-040",
    title: "截交线 · 相贯线典型例题集",
    type: "doc",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-028", "kn-mech-029"],
    courseIds: ["course-mech-draw"],
    description: "李老师整理的 30 例截交相贯典型题，学生最常错题集中区。",
    sizeMb: 5.6,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-10-08T14:00:00+08:00",
    tags: ["难点", "习题集"],
  },
  {
    id: "res-m-041",
    title: "组合体三视图绘制示范 · 轴承座",
    type: "video",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-030", "kn-mech-031", "kn-mech-034"],
    courseIds: ["course-mech-draw"],
    description: "完整示范：由立体到三视图的分解→绘制→检查全过程。",
    duration: "12:35",
    sizeMb: 85,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-10-10T09:00:00+08:00",
    thumbnailUrl: "/thumbs/res-m-041.png",
    tags: ["示范视频", "焦点"],
  },
  {
    id: "res-m-042",
    title: "组合体三视图 · 讲义 v3",
    type: "doc",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-030", "kn-mech-031", "kn-mech-032"],
    courseIds: ["course-mech-draw"],
    description: "AI 教学设计生成的讲义，经李老师复核发布。",
    sizeMb: 6.2,
    uploaderTeacherId: "t-li",
    uploadedAt: "2026-03-20T18:30:00+08:00",
    thumbnailUrl: "/thumbs/res-m-042.png",
    tags: ["讲义", "焦点", "AI生成"],
    isAiGenerated: true,
  },
  {
    id: "res-m-043",
    title: "组合体三视图 · 思维导图",
    type: "image",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-030", "kn-mech-031", "kn-mech-034"],
    courseIds: ["course-mech-draw"],
    description: "AI 生成的思维导图，覆盖组合体绘制要点。",
    sizeMb: 1.3,
    uploaderTeacherId: "t-li",
    uploadedAt: "2026-03-20T18:35:00+08:00",
    tags: ["思维导图", "AI生成"],
    isAiGenerated: true,
  },
  {
    id: "res-m-044",
    title: "轴承座 STL 模型",
    type: "dataset",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-031", "kn-mech-059"],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "三视图教学配套的 STL 模型，可用于 3D 打印或 Unity 观察。",
    sizeMb: 12,
    uploaderTeacherId: "t-wang",
    uploadedAt: "2026-03-12T09:00:00+08:00",
    tags: ["3D模型", "教具"],
  },

  // ==================== 机械工程 · 机件表达 ====================
  {
    id: "res-m-050",
    title: "剖视图与断面图 · 讲义",
    type: "doc",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-039", "kn-mech-040"],
    courseIds: ["course-mech-draw"],
    description: "剖视图的全剖、半剖、局部剖详解。",
    sizeMb: 3.1,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-10-15T14:00:00+08:00",
    tags: ["讲义", "表达"],
  },
  {
    id: "res-m-051",
    title: "剖视图画法 · 微课视频",
    type: "video",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-039"],
    courseIds: ["course-mech-draw"],
    description: "15 分钟搞懂剖视图三种常用画法。",
    duration: "15:10",
    sizeMb: 98,
    uploaderTeacherId: "t-wang",
    uploadedAt: "2025-10-16T10:00:00+08:00",
    tags: ["微课", "表达"],
  },

  // ==================== 机械工程 · 标准件 ====================
  {
    id: "res-m-060",
    title: "螺纹紧固件标准规格速查表",
    type: "dataset",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-042", "kn-mech-043", "kn-mech-044"],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "GB/T 5782/5783/5784 等螺栓螺钉参数表 Excel。",
    sizeMb: 0.4,
    uploaderTeacherId: "t-chen",
    uploadedAt: "2025-11-02T11:00:00+08:00",
    tags: ["速查表", "标准件"],
  },
  {
    id: "res-m-061",
    title: "螺纹画法动画",
    type: "video",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-043"],
    courseIds: ["course-mech-draw"],
    description: "外/内螺纹与连接规定画法动画。",
    duration: "04:55",
    sizeMb: 22,
    uploaderTeacherId: "t-chen",
    uploadedAt: "2025-11-03T14:00:00+08:00",
    tags: ["动画", "螺纹"],
  },

  // ==================== 机械工程 · 零件图与装配图 ====================
  {
    id: "res-m-070",
    title: "零件图模板 DWG（含标题栏）",
    type: "code",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-048", "kn-mech-006", "kn-mech-054"],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "学生作业可直接打开使用的 DWG 模板。",
    sizeMb: 0.7,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-11-18T09:00:00+08:00",
    tags: ["模板", "DWG"],
  },
  {
    id: "res-m-071",
    title: "装配图识读案例 · 齿轮油泵",
    type: "doc",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-052", "kn-mech-053", "kn-mech-047"],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "从装配图还原零件结构与装配关系的完整案例讲解。",
    sizeMb: 7.5,
    uploaderTeacherId: "t-chen",
    uploadedAt: "2025-12-05T10:00:00+08:00",
    tags: ["案例", "装配图"],
  },

  // ==================== 机械工程 · CAD/三维建模 ====================
  {
    id: "res-m-080",
    title: "AutoCAD 2024 命令速查手册",
    type: "doc",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-054"],
    courseIds: ["course-mech-draw"],
    description: "常用 180 个命令速查。",
    sizeMb: 2.3,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-05T10:00:00+08:00",
    tags: ["CAD", "速查"],
  },
  {
    id: "res-m-081",
    title: "AutoCAD 图层管理实战",
    type: "video",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-055"],
    courseIds: ["course-mech-draw"],
    description: "10 分钟把图层彻底弄明白。",
    duration: "10:22",
    sizeMb: 68,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-26T14:00:00+08:00",
    tags: ["CAD", "图层"],
  },
  {
    id: "res-m-082",
    title: "SolidWorks 入门 · 草图与特征建模",
    type: "video",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-058", "kn-mech-059"],
    courseIds: ["course-mech-draw"],
    description: "25 分钟从零开始学 SW 建模。",
    duration: "25:40",
    sizeMb: 180,
    uploaderTeacherId: "t-chen",
    uploadedAt: "2025-12-18T09:00:00+08:00",
    thumbnailUrl: "/thumbs/res-m-082.png",
    tags: ["SolidWorks", "入门"],
  },
  {
    id: "res-m-083",
    title: "标准件库（SolidWorks Toolbox 常用件）",
    type: "dataset",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-044", "kn-mech-059", "kn-mech-060"],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "常用螺栓/键/销的 SW 模型库。",
    sizeMb: 210,
    uploaderTeacherId: "t-chen",
    uploadedAt: "2025-12-19T10:30:00+08:00",
    tags: ["SolidWorks", "标准件"],
  },

  // ==================== 机械工程 · 综合题库 ====================
  {
    id: "res-m-090",
    title: "《机械制图与CAD》期中题库",
    type: "quiz",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-014", "kn-mech-015", "kn-mech-028", "kn-mech-029", "kn-mech-031", "kn-mech-039",
    ],
    courseIds: ["course-mech-draw"],
    description: "80 题，期中复盘用。",
    sizeMb: 1.8,
    uploaderTeacherId: "t-li",
    uploadedAt: "2026-04-10T09:00:00+08:00",
    tags: ["期中", "题库"],
  },

  // ==================== 法学 ====================
  {
    id: "res-l-001",
    title: "《民法典》总则编全文解读",
    type: "doc",
    professionId: "prof-law",
    knowledgeNodeIds: ["kn-law-001", "kn-law-002", "kn-law-005"],
    courseIds: ["course-law-civil"],
    description: "赵文静老师主编的总则编条文逐条解读，42 页。",
    sizeMb: 3.6,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-09-01T09:00:00+08:00",
    tags: ["民法典", "必读"],
  },
  {
    id: "res-l-002",
    title: "民事法律行为效力四态课件",
    type: "ppt",
    professionId: "prof-law",
    knowledgeNodeIds: ["kn-law-012", "kn-law-014"],
    courseIds: ["course-law-civil"],
    description: "有效/无效/可撤销/效力待定四态对比讲解。",
    sizeMb: 4.2,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-10-10T14:00:00+08:00",
    tags: ["课件", "法律行为"],
  },
  {
    id: "res-l-003",
    title: "指导性案例选编（民事类）",
    type: "doc",
    professionId: "prof-law",
    knowledgeNodeIds: ["kn-law-012", "kn-law-014", "kn-law-018"],
    courseIds: ["course-law-civil"],
    description: "最高人民法院指导性案例 20 例精选，带裁判要点。",
    sizeMb: 5.1,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-10-15T10:00:00+08:00",
    tags: ["案例", "精选"],
  },
  {
    id: "res-l-004",
    title: "代理制度辨析 · 视频讲座",
    type: "video",
    professionId: "prof-law",
    knowledgeNodeIds: ["kn-law-015"],
    courseIds: ["course-law-civil"],
    description: "委托代理 / 法定代理 / 无权代理 / 表见代理辨析。",
    duration: "22:30",
    sizeMb: 120,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-11-05T10:00:00+08:00",
    tags: ["视频", "代理"],
  },
  {
    id: "res-l-005",
    title: "法条检索技巧 · 微课",
    type: "audio",
    professionId: "prof-law",
    knowledgeNodeIds: ["kn-law-005"],
    courseIds: ["course-law-civil"],
    description: "9 分钟教你高效检索法条。",
    duration: "09:15",
    sizeMb: 8.6,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-11-06T10:00:00+08:00",
    tags: ["微课", "检索"],
  },
  {
    id: "res-l-006",
    title: "民法典总则编期末模拟题库",
    type: "quiz",
    professionId: "prof-law",
    knowledgeNodeIds: [
      "kn-law-001", "kn-law-009", "kn-law-012", "kn-law-014", "kn-law-015", "kn-law-020", "kn-law-021",
    ],
    courseIds: ["course-law-civil"],
    description: "100 题：单选 40 + 多选 20 + 案例 40。",
    sizeMb: 1.3,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-12-20T14:00:00+08:00",
    tags: ["题库", "期末"],
  },

  // ==================== 护理学 ====================
  {
    id: "res-n-001",
    title: "无菌操作十项原则 · 课件",
    type: "ppt",
    professionId: "prof-nurse",
    knowledgeNodeIds: ["kn-nur-008", "kn-nur-009"],
    courseIds: ["course-nurse-basic"],
    description: "王丽华老师的经典课件，班班必用。",
    sizeMb: 5.8,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-09-02T09:00:00+08:00",
    tags: ["无菌", "课件"],
  },
  {
    id: "res-n-002",
    title: "无菌技术操作示范（完整流程）",
    type: "video",
    professionId: "prof-nurse",
    knowledgeNodeIds: ["kn-nur-009"],
    courseIds: ["course-nurse-basic"],
    description: "18 分钟完整示范。",
    duration: "18:06",
    sizeMb: 126,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-09-03T10:00:00+08:00",
    thumbnailUrl: "/thumbs/res-n-002.png",
    tags: ["示范", "核心"],
  },
  {
    id: "res-n-003",
    title: "生命体征测量 · 肌肉注射 · 静脉输液三大操作手册",
    type: "doc",
    professionId: "prof-nurse",
    knowledgeNodeIds: ["kn-nur-011", "kn-nur-012", "kn-nur-013", "kn-nur-016", "kn-nur-017"],
    courseIds: ["course-nurse-basic"],
    description: "图文并茂，学生人手一份。",
    sizeMb: 7.2,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-09-10T15:00:00+08:00",
    tags: ["手册", "操作"],
  },
  {
    id: "res-n-004",
    title: "病人卧位与体位图解",
    type: "image",
    professionId: "prof-nurse",
    knowledgeNodeIds: ["kn-nur-006"],
    courseIds: ["course-nurse-basic"],
    description: "12 张高清图解，涵盖仰卧/侧卧/半坐卧等常用卧位。",
    sizeMb: 3.1,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-09-12T09:30:00+08:00",
    tags: ["图解", "卧位"],
  },
  {
    id: "res-n-005",
    title: "基础护理技能评分标准表",
    type: "dataset",
    professionId: "prof-nurse",
    knowledgeNodeIds: ["kn-nur-009", "kn-nur-011", "kn-nur-016", "kn-nur-017"],
    courseIds: ["course-nurse-basic"],
    description: "全国护理技能竞赛评分表格（Excel）。",
    sizeMb: 0.3,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-09-15T09:00:00+08:00",
    tags: ["评分", "竞赛"],
  },
  {
    id: "res-n-006",
    title: "基础护理学期中题库",
    type: "quiz",
    professionId: "prof-nurse",
    knowledgeNodeIds: [
      "kn-nur-002", "kn-nur-009", "kn-nur-011", "kn-nur-013", "kn-nur-016", "kn-nur-017",
    ],
    courseIds: ["course-nurse-basic"],
    description: "60 题，含操作步骤题。",
    sizeMb: 1.1,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-11-10T14:00:00+08:00",
    tags: ["题库", "期中"],
  },
];
