import type { Resource, ResourceType } from "./types";

/**
 * 教学资源数据
 *
 * 新规则：资源不是图谱节点，也不再直接挂载知识点。
 * 资源作为课程/实训的资料内容，通过 courseIds / trainingIds 绑定到教学活动。
 */

function res(args: {
  id: string;
  title: string;
  type: ResourceType;
  courseIds: string[];
  trainingIds?: string[];
  description: string;
  uploaderTeacherId: string;
  uploadedAt: string;
  tags: string[];
  duration?: string;
  sizeMb?: number;
  thumbnailUrl?: string;
  isAiGenerated?: boolean;
}): Resource {
  return {
    professionId: "prof-mech",
    sizeMb: 1,
    ...args,
    trainingIds: args.trainingIds ?? [],
  };
}

export const resources: Resource[] = [
  res({
    id: "res-m-001",
    title: "GB/T 14689-2008 技术制图 图纸幅面和格式（全文）",
    type: "doc",
    courseIds: ["course-mech-draw", "course-mech-intro"],
    description: "国家标准全文 PDF，作为制图基础与工程规范素养的必读资料。",
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-01T08:10:00+08:00",
    thumbnailUrl: "/thumbs/res-m-001.png",
    tags: ["国标", "必读", "规范"],
    sizeMb: 1.4,
  }),
  res({
    id: "res-m-002",
    title: "制图基础概述 · 第一讲课件",
    type: "ppt",
    courseIds: ["course-mech-draw"],
    description: "覆盖图幅、比例、字体、图线与尺寸标注的入门课件。",
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-01T09:00:00+08:00",
    thumbnailUrl: "/thumbs/res-m-002.png",
    tags: ["课件", "制图基础"],
    sizeMb: 8.6,
  }),
  res({
    id: "res-m-003",
    title: "工程字长仿宋体书写示范",
    type: "video",
    courseIds: ["course-mech-draw"],
    trainingIds: ["train-m-001"],
    description: "手把手示范工程字书写，配合徒手草图和图纸规范训练。",
    duration: "08:12",
    sizeMb: 55,
    uploaderTeacherId: "t-wang",
    uploadedAt: "2025-09-03T10:30:00+08:00",
    thumbnailUrl: "/thumbs/res-m-003.png",
    tags: ["示范", "视频"],
  }),
  res({
    id: "res-m-004",
    title: "九种基本图线速查图",
    type: "image",
    courseIds: ["course-mech-draw"],
    description: "一张图帮助学生对齐图线使用规则。",
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-04T14:20:00+08:00",
    thumbnailUrl: "/thumbs/res-m-004.png",
    tags: ["速查", "图线"],
    sizeMb: 0.8,
  }),
  res({
    id: "res-m-010",
    title: "圆弧连接 20 例精讲",
    type: "doc",
    courseIds: ["course-mech-draw"],
    trainingIds: ["train-m-002"],
    description: "从两直线圆弧连接到复杂过渡，20 例经典题解。",
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-10T09:00:00+08:00",
    tags: ["习题", "几何作图"],
    sizeMb: 4.2,
  }),
  res({
    id: "res-m-011",
    title: "椭圆四心近似法动画演示",
    type: "video",
    courseIds: ["course-mech-draw"],
    trainingIds: ["train-m-002"],
    description: "动画讲解四心圆弧法作椭圆原理。",
    duration: "06:18",
    sizeMb: 35,
    uploaderTeacherId: "t-wang",
    uploadedAt: "2025-09-11T15:20:00+08:00",
    tags: ["动画", "几何"],
  }),
  res({
    id: "res-m-020",
    title: "三视图形成动态演示",
    type: "video",
    courseIds: ["course-mech-draw"],
    trainingIds: ["train-m-003"],
    description: "三投影面展开过程的 3D 动画，支撑投影与三视图教学。",
    duration: "05:42",
    sizeMb: 42,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-18T10:00:00+08:00",
    thumbnailUrl: "/thumbs/res-m-020.png",
    tags: ["动画", "核心"],
  }),
  res({
    id: "res-m-021",
    title: "长对正高平齐宽相等口诀解析",
    type: "audio",
    courseIds: ["course-mech-draw"],
    description: "4 分钟播客，用于课前预习和课后复习。",
    duration: "04:05",
    sizeMb: 3.8,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-18T11:00:00+08:00",
    tags: ["播客", "口诀"],
  }),
  res({
    id: "res-m-022",
    title: "投影基础练习题库（100 题）",
    type: "quiz",
    courseIds: ["course-mech-draw"],
    description: "含选择题、判断题和读图题，用于投影基础阶段评价。",
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-20T13:00:00+08:00",
    tags: ["题库", "投影"],
    sizeMb: 2.1,
  }),
  res({
    id: "res-m-030",
    title: "点线面投影互动课件（H5）",
    type: "ppt",
    courseIds: ["course-mech-draw"],
    description: "可拖动点、线、面观察三视图变化的互动课件。",
    sizeMb: 18,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-25T09:30:00+08:00",
    thumbnailUrl: "/thumbs/res-m-030.png",
    tags: ["互动", "课件"],
    isAiGenerated: true,
  }),
  res({
    id: "res-m-040",
    title: "截交线 · 相贯线典型例题集",
    type: "doc",
    courseIds: ["course-mech-draw"],
    description: "30 例截交相贯典型题，配合错题集中讲评。",
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-10-08T14:00:00+08:00",
    tags: ["难点", "习题集"],
    sizeMb: 5.6,
  }),
  res({
    id: "res-m-041",
    title: "组合体三视图绘制示范 · 轴承座",
    type: "video",
    courseIds: ["course-mech-draw"],
    trainingIds: ["train-m-003"],
    description: "完整示范：由立体到三视图的分解、绘制与检查全过程。",
    duration: "12:35",
    sizeMb: 85,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-10-10T09:00:00+08:00",
    thumbnailUrl: "/thumbs/res-m-041.png",
    tags: ["示范视频", "主线"],
  }),
  res({
    id: "res-m-042",
    title: "组合体三视图 · 讲义 v3",
    type: "doc",
    courseIds: ["course-mech-draw"],
    trainingIds: ["train-m-003"],
    description: "AI 教学设计生成的讲义，经李老师复核发布。",
    sizeMb: 6.2,
    uploaderTeacherId: "t-li",
    uploadedAt: "2026-03-20T18:30:00+08:00",
    thumbnailUrl: "/thumbs/res-m-042.png",
    tags: ["讲义", "主线", "AI生成"],
    isAiGenerated: true,
  }),
  res({
    id: "res-m-043",
    title: "组合体三视图 · 思维导图",
    type: "image",
    courseIds: ["course-mech-draw"],
    trainingIds: ["train-m-003"],
    description: "AI 生成的思维导图，覆盖组合体绘制要点。",
    uploaderTeacherId: "t-li",
    uploadedAt: "2026-03-20T18:35:00+08:00",
    tags: ["思维导图", "AI生成"],
    isAiGenerated: true,
    sizeMb: 1.3,
  }),
  res({
    id: "res-m-044",
    title: "轴承座 STL 模型",
    type: "dataset",
    courseIds: ["course-mech-draw", "course-mech-design"],
    trainingIds: ["train-m-003", "train-m-005"],
    description: "三视图教学配套的 STL 模型，可用于 3D 打印或三维观察。",
    sizeMb: 12,
    uploaderTeacherId: "t-wang",
    uploadedAt: "2026-03-12T09:00:00+08:00",
    tags: ["3D模型", "教具"],
  }),
  res({
    id: "res-m-050",
    title: "剖视图与断面图 · 讲义",
    type: "doc",
    courseIds: ["course-mech-draw"],
    description: "剖视图的全剖、半剖、局部剖详解。",
    sizeMb: 3.1,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-10-15T14:00:00+08:00",
    tags: ["讲义", "表达"],
  }),
  res({
    id: "res-m-051",
    title: "剖视图画法 · 微课视频",
    type: "video",
    courseIds: ["course-mech-draw"],
    description: "15 分钟讲解剖视图三种常用画法。",
    duration: "15:10",
    sizeMb: 98,
    uploaderTeacherId: "t-wang",
    uploadedAt: "2025-10-16T10:00:00+08:00",
    tags: ["微课", "表达"],
  }),
  res({
    id: "res-m-060",
    title: "螺纹紧固件标准规格速查表",
    type: "dataset",
    courseIds: ["course-mech-draw", "course-mech-design"],
    trainingIds: ["train-m-006"],
    description: "常见螺栓螺钉参数表，支撑标准件表达。",
    sizeMb: 0.4,
    uploaderTeacherId: "t-chen",
    uploadedAt: "2025-11-02T11:00:00+08:00",
    tags: ["速查表", "标准件"],
  }),
  res({
    id: "res-m-061",
    title: "螺纹画法动画",
    type: "video",
    courseIds: ["course-mech-draw"],
    description: "外螺纹、内螺纹与连接规定画法动画。",
    duration: "04:55",
    sizeMb: 22,
    uploaderTeacherId: "t-chen",
    uploadedAt: "2025-11-03T14:00:00+08:00",
    tags: ["动画", "螺纹"],
  }),
  res({
    id: "res-m-070",
    title: "零件图模板 DWG（含标题栏）",
    type: "code",
    courseIds: ["course-mech-draw", "course-mech-design"],
    trainingIds: ["train-m-004", "train-m-007"],
    description: "学生作业可直接打开使用的 DWG 模板。",
    sizeMb: 0.7,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-11-18T09:00:00+08:00",
    tags: ["模板", "DWG"],
  }),
  res({
    id: "res-m-071",
    title: "装配图识读案例 · 齿轮油泵",
    type: "doc",
    courseIds: ["course-mech-draw", "course-mech-design"],
    trainingIds: ["train-m-006"],
    description: "从装配图还原零件结构与装配关系的完整案例。",
    sizeMb: 7.5,
    uploaderTeacherId: "t-chen",
    uploadedAt: "2025-12-05T10:00:00+08:00",
    tags: ["案例", "装配图"],
  }),
  res({
    id: "res-m-080",
    title: "AutoCAD 2024 命令速查手册",
    type: "doc",
    courseIds: ["course-mech-draw"],
    trainingIds: ["train-m-004"],
    description: "常用 180 个命令速查。",
    sizeMb: 2.3,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-05T10:00:00+08:00",
    tags: ["CAD", "速查"],
  }),
  res({
    id: "res-m-081",
    title: "AutoCAD 图层管理实战",
    type: "video",
    courseIds: ["course-mech-draw"],
    trainingIds: ["train-m-004"],
    description: "10 分钟讲解图层建立、管理与出图规范。",
    duration: "10:22",
    sizeMb: 68,
    uploaderTeacherId: "t-li",
    uploadedAt: "2025-09-26T14:00:00+08:00",
    tags: ["CAD", "图层"],
  }),
  res({
    id: "res-m-082",
    title: "SolidWorks 入门 · 草图与特征建模",
    type: "video",
    courseIds: ["course-mech-draw", "course-mech-design"],
    trainingIds: ["train-m-005"],
    description: "25 分钟从零开始学习 SolidWorks 建模。",
    duration: "25:40",
    sizeMb: 180,
    uploaderTeacherId: "t-chen",
    uploadedAt: "2025-12-18T09:00:00+08:00",
    thumbnailUrl: "/thumbs/res-m-082.png",
    tags: ["SolidWorks", "入门"],
  }),
  res({
    id: "res-m-083",
    title: "标准件库（SolidWorks Toolbox 常用件）",
    type: "dataset",
    courseIds: ["course-mech-draw", "course-mech-design"],
    trainingIds: ["train-m-005", "train-m-008"],
    description: "常用螺栓、键、销的 SolidWorks 模型库。",
    sizeMb: 210,
    uploaderTeacherId: "t-chen",
    uploadedAt: "2025-12-19T10:30:00+08:00",
    tags: ["SolidWorks", "标准件"],
  }),
  res({
    id: "res-m-090",
    title: "《机械制图与CAD》期中题库",
    type: "quiz",
    courseIds: ["course-mech-draw"],
    description: "80 题，服务期中复盘和错题分析。",
    sizeMb: 1.8,
    uploaderTeacherId: "t-li",
    uploadedAt: "2026-04-10T09:00:00+08:00",
    tags: ["期中", "题库"],
  }),
  res({
    id: "res-m-091",
    title: "极限与配合选用速查手册（机械类）",
    type: "doc",
    courseIds: ["course-mech-tolerance"],
    trainingIds: ["train-m-009"],
    description: "常用配合实例与工艺对照表。",
    sizeMb: 3.6,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-09-01T09:00:00+08:00",
    tags: ["公差", "必读"],
  }),
  res({
    id: "res-m-092",
    title: "形位公差与基准体系课件",
    type: "ppt",
    courseIds: ["course-mech-tolerance"],
    trainingIds: ["train-m-009"],
    description: "第一基准、第二基准选择策略与典型零件标注。",
    sizeMb: 4.2,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-10-10T14:00:00+08:00",
    tags: ["课件", "形位公差"],
  }),
  res({
    id: "res-m-093",
    title: "粗糙度与功能表面案例集",
    type: "doc",
    courseIds: ["course-mech-tolerance", "course-mech-process"],
    description: "密封面、滑动面、非接触面 Ra 取值工程案例。",
    sizeMb: 5.1,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-10-15T10:00:00+08:00",
    tags: ["案例", "表面质量"],
  }),
  res({
    id: "res-m-094",
    title: "三坐标测量报告解读 · 微课",
    type: "video",
    courseIds: ["course-mech-tolerance"],
    trainingIds: ["train-m-009"],
    description: "对照图纸阅读 CMM 输出与误差分解。",
    duration: "22:30",
    sizeMb: 120,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-11-05T10:00:00+08:00",
    tags: ["视频", "检测"],
  }),
  res({
    id: "res-m-095",
    title: "工艺规程模板与填写说明",
    type: "audio",
    courseIds: ["course-mech-process"],
    trainingIds: ["train-m-008"],
    description: "讲解工序卡字段与质量控制点设置。",
    duration: "12:10",
    sizeMb: 8.6,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-11-06T10:00:00+08:00",
    tags: ["微课", "工艺"],
  }),
  res({
    id: "res-m-096",
    title: "互换性与技术测量期中题库",
    type: "quiz",
    courseIds: ["course-mech-tolerance"],
    description: "70 题：概念、标注纠错和检测方案简答。",
    sizeMb: 1.3,
    uploaderTeacherId: "t-wanglh",
    uploadedAt: "2025-12-20T14:00:00+08:00",
    tags: ["题库", "期中"],
  }),
  res({
    id: "res-m-097",
    title: "工业机器人安全互锁设计清单",
    type: "ppt",
    courseIds: ["course-mech-robotics"],
    trainingIds: ["train-m-010", "train-m-011"],
    description: "围栏、光栅、急停、双联阀检查项与课堂演示脚本。",
    sizeMb: 5.8,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-09-02T09:00:00+08:00",
    tags: ["安全", "课件"],
  }),
  res({
    id: "res-m-098",
    title: "示教编程与 TCP 标定示范",
    type: "video",
    courseIds: ["course-mech-robotics"],
    trainingIds: ["train-m-010"],
    description: "20 分钟完整示范，含常见偏移纠错。",
    duration: "20:06",
    sizeMb: 126,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-09-03T10:00:00+08:00",
    thumbnailUrl: "/thumbs/res-m-098.png",
    tags: ["示范", "示教"],
  }),
  res({
    id: "res-m-099",
    title: "离线仿真—现场标定对照手册",
    type: "doc",
    courseIds: ["course-mech-robotics"],
    trainingIds: ["train-m-010", "train-m-008"],
    description: "节拍差异排查表与工装导入检查项。",
    sizeMb: 7.2,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-09-10T15:00:00+08:00",
    tags: ["手册", "仿真"],
  }),
  res({
    id: "res-m-100",
    title: "典型液压回路原理图册",
    type: "image",
    courseIds: ["course-mech-hydraulic"],
    trainingIds: ["train-m-011"],
    description: "减压、调速、换向、锁紧等 10 张高清原理图。",
    sizeMb: 3.1,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-09-12T09:30:00+08:00",
    tags: ["图解", "液压"],
  }),
  res({
    id: "res-m-101",
    title: "机械工程专业导论 · 产业地图数据集",
    type: "dataset",
    courseIds: ["course-mech-intro"],
    trainingIds: ["train-m-009"],
    description: "装备制造企业岗位、能力、课程映射表。",
    sizeMb: 0.3,
    uploaderTeacherId: "t-sun",
    uploadedAt: "2025-09-15T09:00:00+08:00",
    tags: ["导论", "岗位"],
  }),
  res({
    id: "res-m-102",
    title: "工业机器人期中题库",
    type: "quiz",
    courseIds: ["course-mech-robotics"],
    description: "55 题：坐标系、示教、仿真与安全。",
    sizeMb: 1.1,
    uploaderTeacherId: "t-zhao",
    uploadedAt: "2025-11-10T14:00:00+08:00",
    tags: ["题库", "期中"],
  }),
];

