import type { TrainingProject } from "./types";

/**
 * 实训项目库数据（~15 个）
 *
 * - 机械 8：以制图/CAD/SolidWorks/测绘/金工为主
 * - 护理 5：基础护理操作实训
 * - 法学 2：模拟法庭/合同起草
 */
export const trainingProjects: TrainingProject[] = [
  // ==================== 机械工程 ====================
  {
    id: "train-m-001",
    name: "徒手草图实训 · 生活物品测绘",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-011", "kn-mech-010", "sk-mech-001", "sk-mech-004"],
    courseIds: ["course-mech-draw"],
    description: "让学生选择一个生活中的机械零件（如把手、插销），以徒手草图形式完成测绘与比例估算。",
    difficulty: "入门",
    estimatedHours: 4,
    goals: ["掌握徒手绘图技能", "养成比例估算习惯", "初步建立测绘意识"],
    deliverables: ["徒手草图 1 张", "实测尺寸记录表"],
    environment: "铅笔、三角板、直尺、卷尺（学生自备）",
    coverUrl: "/covers/train-m-001.jpg",
    ownerTeacherId: "t-li",
    tags: ["入门", "测绘"],
  },
  {
    id: "train-m-002",
    name: "圆弧连接 20 题闯关",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-008", "kn-mech-009"],
    courseIds: ["course-mech-draw"],
    description: "围绕圆弧连接难点设计 20 题闯关实训，AI 自动识别答题准确率并给出针对性反馈。",
    difficulty: "入门",
    estimatedHours: 2,
    goals: ["熟练应用圆弧连接六种类型", "提高徒手作图精度"],
    deliverables: ["闯关答题记录"],
    environment: "平台内置作图画布",
    coverUrl: "/covers/train-m-002.jpg",
    ownerTeacherId: "t-li",
    tags: ["习题闯关"],
  },
  {
    id: "train-m-003",
    name: "组合体三视图绘制实训",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-030", "kn-mech-031", "kn-mech-032", "kn-mech-034",
      "sk-mech-001", "core-mech-002",
    ],
    courseIds: ["course-mech-draw"],
    description: "给定 3 个难度梯度的组合体（轴承座 / 支架 / 连接座），完成三视图绘制与尺寸标注。【主故事线核心实训】",
    difficulty: "进阶",
    estimatedHours: 6,
    goals: [
      "综合运用形体分析法与线面分析法",
      "掌握组合体尺寸标注原则",
      "建立二维-三维自由转换的空间想象力",
    ],
    deliverables: ["3 份 A3 三视图手工图纸", "AI 自动批改反馈卡"],
    environment: "图板、丁字尺、三角板（学生自备）",
    coverUrl: "/covers/train-m-003.jpg",
    ownerTeacherId: "t-li",
    tags: ["核心实训", "焦点", "主线"],
  },
  {
    id: "train-m-004",
    name: "AutoCAD 零件图综合实训 · 齿轮轴",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-048", "kn-mech-049", "kn-mech-050", "kn-mech-051",
      "kn-mech-054", "kn-mech-055", "kn-mech-056", "kn-mech-057",
      "sk-mech-002", "sk-mech-006",
    ],
    courseIds: ["course-mech-draw"],
    description: "使用 AutoCAD 完成齿轮轴零件图的绘制与出图，重点练习图层管理与公差标注。",
    difficulty: "综合",
    estimatedHours: 8,
    goals: ["掌握 AutoCAD 完整绘图流程", "正确标注尺寸公差与表面粗糙度", "按标准出图"],
    deliverables: ["齿轮轴零件图 DWG/PDF 各一份"],
    environment: "AutoCAD 2024 + 学校机房或个人电脑",
    coverUrl: "/covers/train-m-004.jpg",
    ownerTeacherId: "t-li",
    tags: ["综合", "CAD"],
  },
  {
    id: "train-m-005",
    name: "SolidWorks 三维建模实训 · 轴承座",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-058", "kn-mech-059", "kn-mech-060", "sk-mech-003", "core-mech-004",
    ],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "使用 SolidWorks 完成轴承座三维建模，并自动输出二维工程图。",
    difficulty: "进阶",
    estimatedHours: 6,
    goals: ["掌握草图与特征建模流程", "熟悉二维工程图自动生成"],
    deliverables: ["SLDPRT 零件文件", "SLDDRW 工程图文件"],
    environment: "SolidWorks 2024 教育版",
    coverUrl: "/covers/train-m-005.jpg",
    ownerTeacherId: "t-chen",
    tags: ["三维建模"],
  },
  {
    id: "train-m-006",
    name: "装配图识读实训 · 齿轮油泵",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-052", "kn-mech-053", "kn-mech-047", "kn-mech-044", "sk-mech-005",
    ],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "给定齿轮油泵装配图，识读装配关系、工作原理并完成关键零件的拆图。",
    difficulty: "综合",
    estimatedHours: 8,
    goals: ["读懂装配图 5 类尺寸", "完成关键零件的拆图", "理解装配关系"],
    deliverables: ["装配关系分析报告", "3 张拆出的零件图"],
    environment: "图板 + 计算机",
    coverUrl: "/covers/train-m-006.jpg",
    ownerTeacherId: "t-chen",
    tags: ["综合", "装配图"],
  },
  {
    id: "train-m-007",
    name: "零件测绘综合实训",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-048", "kn-mech-049", "kn-mech-050", "kn-mech-033",
      "sk-mech-004", "sk-mech-005", "core-mech-005",
    ],
    courseIds: ["course-mech-design"],
    description: "小组合作完成给定部件（减速器端盖）的测绘，拆绘为 CAD 零件图。",
    difficulty: "综合",
    estimatedHours: 12,
    goals: ["综合运用测绘、绘图、公差选用", "锻炼团队协作"],
    deliverables: ["测绘草图", "CAD 零件图 3 份", "测绘报告"],
    environment: "测绘工具箱 + 机房",
    coverUrl: "/covers/train-m-007.jpg",
    ownerTeacherId: "t-chen",
    tags: ["综合", "团队"],
  },
  {
    id: "train-m-008",
    name: "金工实习 · 工件加工与图纸对应",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-048", "kn-mech-049"],
    courseIds: ["course-mech-practice"],
    description: "进入校办工厂完成一次小工件加工，体验图纸到实物的完整过程。",
    difficulty: "综合",
    estimatedHours: 40,
    goals: ["理解加工工艺", "培养工程规范意识", "建立图纸与实物对应感"],
    deliverables: ["加工工件", "工艺卡", "实习报告"],
    environment: "学校金工实习工厂",
    coverUrl: "/covers/train-m-008.jpg",
    ownerTeacherId: "t-chen",
    tags: ["综合", "金工"],
  },

  // ==================== 护理学 ====================
  {
    id: "train-n-001",
    name: "无菌技术操作实训",
    professionId: "prof-nurse",
    knowledgeNodeIds: ["kn-nur-009", "kn-nur-010", "sk-nur-001", "core-nur-002"],
    courseIds: ["course-nurse-basic"],
    description: "在护理实训室完成戴无菌手套、铺无菌盘、无菌容器使用全流程操作。",
    difficulty: "入门",
    estimatedHours: 4,
    goals: ["熟练完成无菌操作全流程", "养成无菌意识"],
    deliverables: ["操作视频（自拍）", "操作评分表"],
    environment: "护理实训室 + 标准无菌操作器材包",
    coverUrl: "/covers/train-n-001.jpg",
    ownerTeacherId: "t-wanglh",
    tags: ["核心操作", "入门"],
  },
  {
    id: "train-n-002",
    name: "生命体征采集实训",
    professionId: "prof-nurse",
    knowledgeNodeIds: ["kn-nur-011", "kn-nur-012", "kn-nur-013", "sk-nur-002"],
    courseIds: ["course-nurse-basic"],
    description: "两人一组互测体温、脉搏、呼吸、血压，准确书写护理记录。",
    difficulty: "入门",
    estimatedHours: 3,
    goals: ["准确采集 4 项生命体征", "规范书写记录"],
    deliverables: ["体征记录单"],
    environment: "护理实训室 + 标准测量器材",
    coverUrl: "/covers/train-n-002.jpg",
    ownerTeacherId: "t-wanglh",
    tags: ["体征", "入门"],
  },
  {
    id: "train-n-003",
    name: "肌肉注射模拟实训",
    professionId: "prof-nurse",
    knowledgeNodeIds: ["kn-nur-014", "kn-nur-016", "sk-nur-001", "core-nur-002"],
    courseIds: ["course-nurse-basic"],
    description: "在模拟人上完成肌肉注射全流程，包含三查八对与心理护理。",
    difficulty: "进阶",
    estimatedHours: 4,
    goals: ["掌握肌注定位与技术", "熟练三查八对"],
    deliverables: ["模拟操作视频", "评分表"],
    environment: "肌肉注射模拟人 + 注射器套装",
    coverUrl: "/covers/train-n-003.jpg",
    ownerTeacherId: "t-wanglh",
    tags: ["注射", "模拟"],
  },
  {
    id: "train-n-004",
    name: "静脉输液综合实训",
    professionId: "prof-nurse",
    knowledgeNodeIds: ["kn-nur-017", "kn-nur-009", "sk-nur-003", "core-nur-002"],
    courseIds: ["course-nurse-basic"],
    description: "在静脉穿刺模拟手臂上完成静脉输液全流程，含排气、穿刺、调速、更换液体、拔针。",
    difficulty: "综合",
    estimatedHours: 6,
    goals: ["熟练进行静脉穿刺", "处理输液常见故障"],
    deliverables: ["操作评分表", "故障处理情景记录"],
    environment: "静脉穿刺模拟手臂 + 输液装置",
    coverUrl: "/covers/train-n-004.jpg",
    ownerTeacherId: "t-wanglh",
    tags: ["综合", "静脉"],
  },
  {
    id: "train-n-005",
    name: "情景模拟 · 夜班病情观察",
    professionId: "prof-nurse",
    knowledgeNodeIds: ["kn-nur-002", "kn-nur-003", "kn-nur-011", "kn-nur-012", "core-nur-001"],
    courseIds: ["course-nurse-basic"],
    description: "夜班情景模拟：病人血压突升，学生需要完成评估-沟通-干预-记录全流程。",
    difficulty: "综合",
    estimatedHours: 3,
    goals: ["建立临床思维", "锻炼沟通能力"],
    deliverables: ["情景报告", "护理记录"],
    environment: "情景化实训室 + 标准化病人",
    coverUrl: "/covers/train-n-005.jpg",
    ownerTeacherId: "t-wanglh",
    tags: ["情景模拟", "综合"],
  },

  // ==================== 法学 ====================
  {
    id: "train-l-001",
    name: "模拟法庭 · 民事代理案件",
    professionId: "prof-law",
    knowledgeNodeIds: ["kn-law-012", "kn-law-014", "kn-law-015", "sk-law-002", "sk-law-003", "core-law-001"],
    courseIds: ["course-law-civil"],
    description: "围绕一起表见代理纠纷，分组担任原告、被告、法官、书记员进行模拟审判。",
    difficulty: "综合",
    estimatedHours: 8,
    goals: ["掌握民事诉讼流程", "锻炼法庭表达", "巩固代理制度知识"],
    deliverables: ["起诉状 / 答辩状 / 判决书", "模拟视频"],
    environment: "模拟法庭教室 + 道具",
    coverUrl: "/covers/train-l-001.jpg",
    ownerTeacherId: "t-zhao",
    tags: ["模拟法庭", "综合"],
  },
  {
    id: "train-l-002",
    name: "合同审查与起草",
    professionId: "prof-law",
    knowledgeNodeIds: ["kn-law-012", "kn-law-014", "kn-law-018", "sk-law-001", "sk-law-003"],
    courseIds: ["course-law-civil"],
    description: "给定房屋租赁合同模板，找出条款漏洞并起草修订版。",
    difficulty: "进阶",
    estimatedHours: 4,
    goals: ["识别合同风险", "掌握基本起草技巧"],
    deliverables: ["修订版合同", "审查意见书"],
    environment: "线上法律文书平台",
    coverUrl: "/covers/train-l-002.jpg",
    ownerTeacherId: "t-zhao",
    tags: ["起草", "审查"],
  },
];
