import type { TrainingProject } from "./types";

/**
 * 实训项目库数据（20 个，均为机械工程）
 *
 * - 制图 / CAD / 测绘 / 金工 8 项（含主线组合体实训）
 * - 公差检测 / 机器人 / 液压 / 工艺 / 专业认知 7 项（辅线）
 * - 学科内 AI 工具完成作业与任务 5 项（见《学科内 AI 实训与应用》课程）
 */
export const trainingProjects: TrainingProject[] = [
  // ==================== 机械工程 ====================
  {
    id: "train-m-001",
    name: "徒手草图实训 · 生活物品测绘",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-011", "kn-mech-010", "sk-mech-001", "sk-mech-004"],
    courseIds: ["course-mech-draw"],
    description: "让学生选择一个生活中的机械零件（如把手、插销），以徒手草图形式完成测绘与比例估算。",
    difficulty: "入门",
    estimatedHours: 4,
    goals: ["掌握徒手绘图技能", "养成比例估算习惯", "初步建立测绘意识"],
    deliverables: ["徒手草图 1 张", "实测尺寸记录表"],
    environment: "铅笔、三角板、直尺、卷尺（学生自备）",
    coverUrl: "/covers/train-m-001.jpg",
    ownerTeacherId: "t-li",
    tags: ["入门", "测绘"],
  },
  {
    id: "train-m-002",
    name: "圆弧连接 20 题闯关",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-008", "kn-mech-009"],
    courseIds: ["course-mech-draw"],
    description: "围绕圆弧连接难点设计 20 题闯关实训，AI 自动识别答题准确率并给出针对性反馈。",
    difficulty: "入门",
    estimatedHours: 2,
    goals: ["熟练应用圆弧连接六种类型", "提高徒手作图精度"],
    deliverables: ["闯关答题记录"],
    environment: "平台内置作图画布",
    coverUrl: "/covers/train-m-002.jpg",
    ownerTeacherId: "t-li",
    tags: ["习题闯关"],
  },
  {
    id: "train-m-003",
    name: "组合体三视图绘制实训",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-030", "kn-mech-031", "kn-mech-032", "kn-mech-034",
      "sk-mech-001", "core-mech-002",
    ],
    courseIds: ["course-mech-draw"],
    description: "给定 3 个难度梯度的组合体（轴承座 / 支架 / 连接座），完成三视图绘制与尺寸标注。【主故事线核心实训】",
    difficulty: "进阶",
    estimatedHours: 6,
    goals: [
      "综合运用形体分析法与线面分析法",
      "掌握组合体尺寸标注原则",
      "建立二维-三维自由转换的空间想象力",
    ],
    deliverables: ["3 份 A3 三视图手工图纸", "AI 自动批改反馈卡"],
    environment: "图板、丁字尺、三角板（学生自备）",
    coverUrl: "/covers/train-m-003.jpg",
    ownerTeacherId: "t-li",
    tags: ["核心实训", "焦点", "主线"],
  },
  {
    id: "train-m-004",
    name: "AutoCAD 零件图综合实训 · 齿轮轴",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-048", "kn-mech-049", "kn-mech-050", "kn-mech-051",
      "kn-mech-054", "kn-mech-055", "kn-mech-056", "kn-mech-057",
      "sk-mech-002", "sk-mech-006",
    ],
    courseIds: ["course-mech-draw"],
    description: "使用 AutoCAD 完成齿轮轴零件图的绘制与出图，重点练习图层管理与公差标注。",
    difficulty: "综合",
    estimatedHours: 8,
    goals: ["掌握 AutoCAD 完整绘图流程", "正确标注尺寸公差与表面粗糙度", "按标准出图"],
    deliverables: ["齿轮轴零件图 DWG/PDF 各一份"],
    environment: "AutoCAD 2024 + 学校机房或个人电脑",
    coverUrl: "/covers/train-m-004.jpg",
    ownerTeacherId: "t-li",
    tags: ["综合", "CAD"],
  },
  {
    id: "train-m-005",
    name: "SolidWorks 三维建模实训 · 轴承座",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-058", "kn-mech-059", "kn-mech-060", "sk-mech-003", "core-mech-004",
    ],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "使用 SolidWorks 完成轴承座三维建模，并自动输出二维工程图。",
    difficulty: "进阶",
    estimatedHours: 6,
    goals: ["掌握草图与特征建模流程", "熟悉二维工程图自动生成"],
    deliverables: ["SLDPRT 零件文件", "SLDDRW 工程图文件"],
    environment: "SolidWorks 2024 教育版",
    coverUrl: "/covers/train-m-005.jpg",
    ownerTeacherId: "t-chen",
    tags: ["三维建模"],
  },
  {
    id: "train-m-006",
    name: "装配图识读实训 · 齿轮油泵",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-052", "kn-mech-053", "kn-mech-047", "kn-mech-044", "sk-mech-005",
    ],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "给定齿轮油泵装配图，识读装配关系、工作原理并完成关键零件的拆图。",
    difficulty: "综合",
    estimatedHours: 8,
    goals: ["读懂装配图 5 类尺寸", "完成关键零件的拆图", "理解装配关系"],
    deliverables: ["装配关系分析报告", "3 张拆出的零件图"],
    environment: "图板 + 计算机",
    coverUrl: "/covers/train-m-006.jpg",
    ownerTeacherId: "t-chen",
    tags: ["综合", "装配图"],
  },
  {
    id: "train-m-007",
    name: "零件测绘综合实训",
    professionId: "prof-mech",
    knowledgeNodeIds: [
      "kn-mech-048", "kn-mech-049", "kn-mech-050", "kn-mech-033",
      "sk-mech-004", "sk-mech-005", "core-mech-005",
    ],
    courseIds: ["course-mech-design"],
    description: "小组合作完成给定部件（减速器端盖）的测绘，拆绘为 CAD 零件图。",
    difficulty: "综合",
    estimatedHours: 12,
    goals: ["综合运用测绘、绘图、公差选用", "锻炼团队协作"],
    deliverables: ["测绘草图", "CAD 零件图 3 份", "测绘报告"],
    environment: "测绘工具箱 + 机房",
    coverUrl: "/covers/train-m-007.jpg",
    ownerTeacherId: "t-chen",
    tags: ["综合", "团队"],
  },
  {
    id: "train-m-008",
    name: "金工实习 · 工件加工与图纸对应",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-048", "kn-mech-049"],
    courseIds: ["course-mech-practice"],
    description: "进入校办工厂完成一次小工件加工，体验图纸到实物的完整过程。",
    difficulty: "综合",
    estimatedHours: 40,
    goals: ["理解加工工艺", "培养工程规范意识", "建立图纸与实物对应感"],
    deliverables: ["加工工件", "工艺卡", "实习报告"],
    environment: "学校金工实习工厂",
    coverUrl: "/covers/train-m-008.jpg",
    ownerTeacherId: "t-wang",
    tags: ["综合", "金工"],
  },

  // ==================== 辅线 · 检测 / 机器人 / 液压 / 工艺 / 认知 ====================
  {
    id: "train-m-009",
    name: "三坐标测量与公差复验实训",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-049", "kn-mech-050", "kn-mech-051", "sk-mech-006"],
    courseIds: ["course-mech-tolerance"],
    description: "针对上一工序加工件建立测量坐标系，输出关键尺寸与形位误差报告。",
    difficulty: "进阶",
    estimatedHours: 4,
    goals: ["理解测量坐标系与图纸基准关系", "会读 CMM 报告"],
    deliverables: ["测量记录 PDF", "超差分析表"],
    environment: "三坐标测量室",
    coverUrl: "/covers/train-m-009.jpg",
    ownerTeacherId: "t-wanglh",
    tags: ["检测", "公差"],
  },
  {
    id: "train-m-010",
    name: "工业机器人示教与离线仿真联调",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-058", "kn-mech-059", "kn-mech-060", "sk-mech-003"],
    courseIds: ["course-mech-robotics"],
    description: "完成简易搬运工作站示教，并在离线软件中复现与优化节拍。",
    difficulty: "进阶",
    estimatedHours: 6,
    goals: ["掌握 TCP 标定与示教流程", "能对比仿真与现场差异"],
    deliverables: ["示教程序包", "仿真截图与节拍表"],
    environment: "机器人工作站 + 离线仿真机房",
    coverUrl: "/covers/train-m-010.jpg",
    ownerTeacherId: "t-zhao",
    tags: ["机器人", "仿真"],
  },
  {
    id: "train-m-011",
    name: "液压回路装调与压力测试",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-042", "kn-mech-044", "kn-mech-052"],
    courseIds: ["course-mech-hydraulic"],
    description: "在实验台上搭建减压/调速回路，记录压力—流量曲线并解释异常。",
    difficulty: "入门",
    estimatedHours: 4,
    goals: ["读懂液压原理图", "完成基本回路装调"],
    deliverables: ["实验曲线", "故障排查记录"],
    environment: "液压传动实验室",
    coverUrl: "/covers/train-m-011.jpg",
    ownerTeacherId: "t-zhao",
    tags: ["液压", "实验"],
  },
  {
    id: "train-m-012",
    name: "工艺规程编制 · 轴类零件",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-048", "kn-mech-050", "kn-mech-053", "sk-mech-007"],
    courseIds: ["course-mech-process"],
    description: "给定轴类零件图纸，编制工序卡并说明定位基准与量具选用。",
    difficulty: "综合",
    estimatedHours: 6,
    goals: ["能拆分工序", "建立质量控制点意识"],
    deliverables: ["工艺卡", "简短时间—成本说明"],
    environment: "工艺教室 + 典型零件样件",
    coverUrl: "/covers/train-m-012.jpg",
    ownerTeacherId: "t-wanglh",
    tags: ["工艺", "综合"],
  },
  {
    id: "train-m-013",
    name: "专业认知 · 智能产线参观",
    professionId: "prof-mech",
    knowledgeNodeIds: ["core-mech-001", "kn-mech-001", "kn-mech-012"],
    courseIds: ["course-mech-intro"],
    description: "参观校内外智能制造示范线，完成「设备—工序—图纸」对应表。",
    difficulty: "入门",
    estimatedHours: 4,
    goals: ["建立产线级系统观", "理解图纸在制造中的位置"],
    deliverables: ["参观笔记", "工序对应表"],
    environment: "合作企业产线或校内示范线",
    coverUrl: "/covers/train-m-013.jpg",
    ownerTeacherId: "t-sun",
    tags: ["认知", "产线"],
  },
  {
    id: "train-m-014",
    name: "气动分拣回路 · 安全互锁设计",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-052", "kn-mech-053", "core-mech-003"],
    courseIds: ["course-mech-hydraulic", "course-mech-robotics"],
    description: "设计带双联阀与光栅互锁的气动分拣实验回路，撰写安全说明。",
    difficulty: "进阶",
    estimatedHours: 5,
    goals: ["理解气动安全规范", "能画简易气动原理图"],
    deliverables: ["原理图", "安全说明 1 页"],
    environment: "气动综合实验台",
    coverUrl: "/covers/train-m-014.jpg",
    ownerTeacherId: "t-zhao",
    tags: ["气动", "安全"],
  },
  {
    id: "train-m-015",
    name: "装配工位数字孪生入门",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-052", "kn-mech-060", "core-mech-005"],
    courseIds: ["course-mech-robotics", "course-mech-design"],
    description: "将简易夹具装配体导入仿真环境，定义装配顺序与干涉检查。",
    difficulty: "综合",
    estimatedHours: 6,
    goals: ["建立数字孪生概念", "完成干涉报告"],
    deliverables: ["装配顺序视频", "干涉检查截图"],
    environment: "SolidWorks + 仿真插件",
    coverUrl: "/covers/train-m-015.jpg",
    ownerTeacherId: "t-chen",
    tags: ["孪生", "装配"],
  },

  // ==================== 学科内 AI 实训（生成式工具完成作业 / 任务）====================
  {
    id: "train-m-016",
    name: "对话式 AI 辅助零件图读图 · 尺寸清单作业",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-065", "kn-mech-066", "kn-mech-048", "sk-mech-005", "sk-mech-008"],
    courseIds: ["course-mech-ai-lab", "course-mech-draw"],
    description:
      "给定一张典型轴类零件图，使用教师指定的大模型工具：分步提问完成视图关系说明、关键尺寸与公差条目整理，并人工核对后与平台 AI 批改对照。",
    difficulty: "入门",
    estimatedHours: 3,
    goals: ["会写分层提示词（先总览后细节）", "能对 AI 输出做图纸级事实核验", "形成可提交的尺寸清单作业"],
    deliverables: ["提示词与对话记录（脱敏）", "尺寸与公差清单表", "人工订正批注截图"],
    environment: "校园网许可的对话式大模型 + PDF 读图",
    coverUrl: "/covers/train-m-004.jpg",
    ownerTeacherId: "t-li",
    tags: ["AI实训", "读图作业", "大模型"],
  },
  {
    id: "train-m-017",
    name: "AI 辅助液压实验报告 · 数据处理段落",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-065", "kn-mech-066", "kn-mech-042", "kn-mech-044", "sk-mech-008"],
    courseIds: ["course-mech-ai-lab", "course-mech-hydraulic"],
    description:
      "根据实验台实测数据，使用 AI 生成「现象—原因—结论」框架草稿，学生手写填入真实数值与曲线，并删除一切虚构数据。",
    difficulty: "进阶",
    estimatedHours: 4,
    goals: ["区分 AI 生成框架与实验事实边界", "掌握实验报告必备段落结构", "杜绝数据捏造"],
    deliverables: ["实验原始数据表", "带修订痕迹的报告 DOC/PDF", "AI 使用声明（工具名与用途）"],
    environment: "液压实验台 + 文档编辑器",
    coverUrl: "/covers/train-m-011.jpg",
    ownerTeacherId: "t-zhao",
    tags: ["AI实训", "实验报告", "液压"],
  },
  {
    id: "train-m-018",
    name: "文生图 + 徒手草图 · 支架概念方案任务",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-065", "kn-mech-067", "kn-mech-031", "sk-mech-001", "sk-mech-008"],
    courseIds: ["course-mech-ai-lab", "course-mech-draw", "course-mech-design"],
    description:
      "针对「轻量化支架」设计任务，用文生图工具生成 3 款外观发散方案，择其一用徒手草图转译为可加工结构，并标注与 SolidWorks 课衔接的建模要点。",
    difficulty: "进阶",
    estimatedHours: 5,
    goals: ["理解文生图在方案阶段的定位", "完成 AI 概念到工程草图的转译", "为后续三维建模留好约束思路"],
    deliverables: ["文生图方案拼图 1 页", "选定方案的徒手三视图草图", "设计决策说明（200 字内）"],
    environment: "平台许可的文生图工具 + 纸笔",
    coverUrl: "/covers/train-m-005.jpg",
    ownerTeacherId: "t-chen",
    tags: ["AI实训", "概念设计", "文生图"],
  },
  {
    id: "train-m-019",
    name: "大模型辅助机器人工作站 · 安全检查表作业",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-065", "kn-mech-066", "kn-mech-063", "kn-mech-064", "sk-mech-008"],
    courseIds: ["course-mech-ai-lab", "course-mech-robotics"],
    description:
      "围绕简易搬运工作站，让 AI 按国标/校内规范条目生成检查表初稿，学生结合现场照片增删条款并完成一次桌面推演签字栏。",
    difficulty: "综合",
    estimatedHours: 5,
    goals: ["将规范语言转化为可执行检查项", "识别 AI 遗漏的互锁与急停场景", "形成可归档的安全文档"],
    deliverables: ["检查表终稿 PDF", "与初稿对比的修订说明", "现场或仿真环境佐证图"],
    environment: "机器人工作站或离线仿真截图 + 对话式大模型",
    coverUrl: "/covers/train-m-010.jpg",
    ownerTeacherId: "t-zhao",
    tags: ["AI实训", "机器人", "安全文档"],
  },
  {
    id: "train-m-020",
    name: "工艺小论文 · AI 大纲与国标引用初稿",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-065", "kn-mech-066", "kn-mech-050", "kn-mech-052", "sk-mech-007", "sk-mech-008"],
    courseIds: ["course-mech-ai-lab", "course-mech-process"],
    description:
      "《机械制造工艺学》课程小论文：用 AI 生成大纲与国标检索线索，学生逐条打开标准原文确认引用，并撰写个人论点段落（查重前须关闭大模型续写）。",
    difficulty: "综合",
    estimatedHours: 8,
    goals: ["建立「AI 线索 + 人工查证」写作流程", "正确引用制图/公差相关国标条目", "理解学术诚信与查重要求"],
    deliverables: ["论文终稿", "国标引用列表（含标准号与页码）", "AI 辅助范围说明"],
    environment: "标准数据库或教材附录 + 文字处理软件",
    coverUrl: "/covers/train-m-012.jpg",
    ownerTeacherId: "t-wanglh",
    tags: ["AI实训", "论文作业", "学术诚信"],
  },
];
