import type { TrainingProject } from "./types";

/**
 * 实训项目库（11 项，与图谱 `train-m-001`…`train-m-011` 一一对应）。
 */
export const trainingProjects: TrainingProject[] = [
  {
    id: "train-m-001",
    name: "徒手草图与测绘工作坊",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-001", "kn-mech-002", "sk-mech-001", "sk-mech-004"],
    courseIds: ["course-mech-draw"],
    description: "从生活中挑一件小零件，徒手草图并完成简单尺寸链，建立「目测—徒手—校对」链路。",
    difficulty: "入门",
    estimatedHours: 4,
    goals: ["掌握徒手绘草图节奏", "能记录可追溯尺寸要点"],
    deliverables: ["徒手草图 1 页", "尺寸记录"],
    environment: "纸笔即可",
    coverUrl: "/covers/train-m-001.jpg",
    ownerTeacherId: "t-li",
    tags: ["入门", "测绘"],
  },
  {
    id: "train-m-002",
    name: "组合体视图专项实训",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-005", "kn-mech-006", "sk-mech-009", "core-mech-002"],
    courseIds: ["course-mech-draw"],
    description: "给定若干组合体任务，完成三视图与关键交线；强调形体分析与投影推理。",
    difficulty: "进阶",
    estimatedHours: 6,
    goals: ["巩固形体分析", "提升交线意识"],
    deliverables: ["三视图作业", "交线说明"],
    environment: "图板或教室",
    coverUrl: "/covers/train-m-003.jpg",
    ownerTeacherId: "t-li",
    tags: ["核心", "组合体"],
  },
  {
    id: "train-m-003",
    name: "AutoCAD 齿轮轴综合实训",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-009", "kn-mech-011", "sk-mech-002", "sk-mech-006"],
    courseIds: ["course-mech-draw"],
    description: "按国标完成齿轮轴零件图与版式出图，练习图层、块与打印空间。",
    difficulty: "综合",
    estimatedHours: 8,
    goals: ["建立完整二维工作流", "正确呈现公差与粗糙度"],
    deliverables: ["DWG/PDF 各一"],
    environment: "AutoCAD 2024",
    coverUrl: "/covers/train-m-004.jpg",
    ownerTeacherId: "t-li",
    tags: ["CAD", "综合"],
  },
  {
    id: "train-m-004",
    name: "SolidWorks 轴承座建模实训",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-012", "sk-mech-003", "core-mech-004"],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "完成轴承座特征建模与工程图输出，衔接装配与出图。",
    difficulty: "进阶",
    estimatedHours: 6,
    goals: ["熟悉特征—装配—工程图闭环"],
    deliverables: ["SLDPRT", "SLDDRW"],
    environment: "SolidWorks 教育版",
    coverUrl: "/covers/train-m-005.jpg",
    ownerTeacherId: "t-chen",
    tags: ["三维", "建模"],
  },
  {
    id: "train-m-005",
    name: "装配图识读与拆装实训",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-010", "kn-mech-008", "sk-mech-005"],
    courseIds: ["course-mech-draw", "course-mech-design"],
    description: "在给定装配图下完成关键零件拆图与装配顺序说明。",
    difficulty: "综合",
    estimatedHours: 8,
    goals: ["读懂装配约束", "能拆出关键零件图"],
    deliverables: ["拆图报告"],
    environment: "图板或机房",
    coverUrl: "/covers/train-m-006.jpg",
    ownerTeacherId: "t-chen",
    tags: ["装配图"],
  },
  {
    id: "train-m-006",
    name: "三坐标测量与公差复检",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-009", "kn-mech-010", "sk-mech-006"],
    courseIds: ["course-mech-tolerance"],
    description: "对加工件建立测量坐标系并输出与设计基准对照的简报。",
    difficulty: "进阶",
    estimatedHours: 4,
    goals: ["理解基准链", "会读检测报告"],
    deliverables: ["测量简报"],
    environment: "CMM 实训室",
    coverUrl: "/covers/train-m-009.jpg",
    ownerTeacherId: "t-wanglh",
    tags: ["检测"],
  },
  {
    id: "train-m-007",
    name: "工业机器人搬运节拍实训",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-014", "sk-mech-003", "sk-mech-012"],
    courseIds: ["course-mech-robotics"],
    description: "示教三点搬运并完成节拍与安全项核对。",
    difficulty: "进阶",
    estimatedHours: 6,
    goals: ["掌握坐标与示教", "能复述互锁与安全项"],
    deliverables: ["示教备份", "节拍表"],
    environment: "工业机器人工作站",
    coverUrl: "/covers/train-m-010.jpg",
    ownerTeacherId: "t-zhao",
    tags: ["机器人"],
  },
  {
    id: "train-m-008",
    name: "金工切削与图纸一致性验证",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-013", "kn-mech-009", "sk-mech-011"],
    courseIds: ["course-mech-practice"],
    description: "车铣小样件并完成「图纸尺寸—实测」对照条目。",
    difficulty: "综合",
    estimatedHours: 40,
    goals: ["建立工艺感", "能解释超差成因"],
    deliverables: ["样件", "对照表"],
    environment: "金工车间",
    coverUrl: "/covers/train-m-008.jpg",
    ownerTeacherId: "t-wang",
    tags: ["金工"],
  },
  {
    id: "train-m-009",
    name: "液压回路装调与压力辨识",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-015", "sk-mech-012"],
    courseIds: ["course-mech-hydraulic"],
    description: "搭建简易压力/调速回路并完成现象记录。",
    difficulty: "入门",
    estimatedHours: 4,
    goals: ["读懂原理草图", "会记录压力曲线"],
    deliverables: ["实验记录"],
    environment: "液压实验台",
    coverUrl: "/covers/train-m-011.jpg",
    ownerTeacherId: "t-zhao",
    tags: ["液压"],
  },
  {
    id: "train-m-010",
    name: "AI 文档辅写与核验工作坊",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-017", "kn-mech-009", "sk-mech-008"],
    courseIds: ["course-mech-ai-lab", "course-mech-draw"],
    description: "在限定提示词模板下生成长度清单草稿，逐项与图纸核验。",
    difficulty: "入门",
    estimatedHours: 3,
    goals: ["区分 AI 草稿与核验责任", "能输出可追溯修订记录"],
    deliverables: ["提示词草稿", "核验批注截图"],
    environment: "平台许可的对话式模型",
    coverUrl: "/covers/train-m-004.jpg",
    ownerTeacherId: "t-li",
    tags: ["AI实训"],
  },
  {
    id: "train-m-011",
    name: "孪生巡检清单入门",
    professionId: "prof-mech",
    knowledgeNodeIds: ["kn-mech-016", "kn-mech-010", "core-mech-005"],
    courseIds: ["course-mech-robotics", "course-mech-design"],
    description: "在示例孪生场景中完成巡检条目勾选与两张截图归档。",
    difficulty: "综合",
    estimatedHours: 5,
    goals: ["建立孪生与装配认知", "能说清条目依据"],
    deliverables: ["巡检表终稿 PDF"],
    environment: "教学孪生沙盘或示例文件",
    coverUrl: "/covers/train-m-011.jpg",
    ownerTeacherId: "t-chen",
    tags: ["孪生"],
  },
];
